"""empty message

Revision ID: 05a812d27afb
Revises: 381814e11467
Create Date: 2019-01-30 06:23:49.115490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a812d27afb'
down_revision = '381814e11467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'create_time')
    # ### end Alembic commands ###
