"""empty message

Revision ID: 26b9a04f8e33
Revises: 7e56f8ee3f2c
Create Date: 2019-01-30 21:14:31.676364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b9a04f8e33'
down_revision = '7e56f8ee3f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_column('users', 'score')
    # ### end Alembic commands ###
