"""empty message

Revision ID: c3a58246094a
Revises: d592d1d9ee5d
Create Date: 2019-02-01 13:20:53.092401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a58246094a'
down_revision = 'd592d1d9ee5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('code_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'code_hash')
    # ### end Alembic commands ###
